#+title: Eleonor's Alternate Stress and Burdens for Lancer: RPG
#+author: Eleonor V.
#+OPTIONS: toc:nil

* Justification and Goals
+I wanna use *Stress* mooooore!! And I want *Harm* as described in the
core rule book!! and being able to juggle them!!+

I want heroes to be able to have more tools to navigate failures and
better, but simple, ways to represent the toll of taking on a mission.

This document intends to keep the detailed Consequences described in
the core rule book, while giving a mechanism to narrowly avoid it by
using Stress.

Importantly, the experience should not punish or frustrate players for
using Stress, but rather promote alternate routes to failure and
agency.

* Stress
In addition to *HP* and *Armor*, your pilot has a *Stress* bar,
represented by an 8-segment clock. It represents your Pilot's ability
to adapt and circumvent their circumstances and even their own
shortcomings. Heroes keep pushing!

The major difference between this and Stress as described in KTB is
that Stress represents the energy and exhaustion that pilots suffer
from fixing their mistakes in the heat of the moment. They get to
avoid consequences entirely, at the cost of their own well-being.

* Resisting Consequences
On failing a *Skill Check*, before receiving a Consequence, you may
automatically ignore /all of it/, as if you had succeeded in the
*Skill Check*, at the cost of *Stress* corresponding to the magnitude
of the *Consequence* avoided. (Refer to KTB, p.88 "Taking Stress" for
levels of *Consequences*, and CRB, p.46 "Consequences" for what those
could be)

|-------------+--------|
| Consequence | Stress |
|-------------+--------|
| Minor       |    1-2 |
| Typical     |    2-3 |
| Major       |    3-6 |
|-------------+--------|

* Burdens
When you would take *Stress* that would exceed your maximum, you
*Break* and obtain a *Burden*, as detailed in _Field Guide: The
Karrakin Trade Baronies_ (p.89) with one exception: You are not
removed from a *Scene* when you *Break*. In addition, once you obtain
a *Burden*, you will suffer an immediate negative effect, as well as a
persistent negative effect which lasts until you fill up that burden's
clock and clear it.

** Immediate effects of Burdens
Your actions has solved the matter at hand, but have caused unforeseen
consequences. At any time after this *Scene*, your Pilot suffers from
consequences different than the ones avoided, and of similar
magnitude. E.g., You avoided damage from gun fire, but eventually, you
run out of ammo much faster than expected.

**** COMMENT Dev Notes
Immediate Effects of burdens should be /complications/ to the
narrative: Something happens down the road. You've used Stress to
avoid consequence, you should not be punished with consequence (right
now). Resisting should always result in avoiding the most immediate
problems. Perhaps, these immediate effects mean you kick the can down
the road in some unforeseen way, rather than punish you right now.

** Long-term effects of Burdens
Long-term effects represent trauma, character flaws, grievances,
prejudices, and other factors that /influence/ the decision-making
process of your Pilot. These are not mechanical penalties, but rather,
tools to guide your role-playing. Use words or short phrases that
reflect your pilot's negative, or uncooperative traits. E.g., After
failing to lock-pick a door, John developed "Self-doubt" in their
skills. They will hesitate to offer their skills when the stakes are
high. John is still very skilled at lock-picking, if they do brave to
make another skill check.

**** COMMENT Dev notes
Taking extra stress is fineee. Raising the cost of /avoiding/
consequences is fiiiine, but Burdens should not punishing you for
existing. They should be raising the cost of weaseling out of
failure. They shouldn't make skill checks harder. They could also be
easier to obtain and easier to get rid of? Then, they just represent
the mounting pressures of /a single mission/ rather than the long-term
attrition of a campaign.

I do have to take into consideration compatibility with KTB/SOTW Bonds
that interact directly with Burdens.
